// src/components/Footer.jsx
import Translate from './Translate';

export default function Footer() {
  const currentYear = new Date().getFullYear();
  return (
    <>
      <footer className="w-full px-4 flex items-center justify-center">
        <div className="h-[70px] flex items-center justify-center">
          <small>
            Made with ❤️ by Michael Liendo &copy; {currentYear} | <Translate />
          </small>
        </div>
      </footer>
    </>
  );
}

// src/lib/components/Footer.svelte
<script lang="ts">
	import LL from '$i18n/i18n-svelte';

	const currentYear = new Date().getFullYear();
</script>

<footer class="w-full px-4 flex items-center justify-center">
	<div class="h-[70px] flex items-center justify-center">
		<small>
			{$LL.LAYOUT.FOOTER.COPYRIGHT({ year: currentYear })}
		</small>
	</div>
</footer>
